In [24]:
import rtree


# https://github.com/Toblerity/rtree/blob/master/docs/source/tutorial.txt
from rtree import index
idx = index.Index()

# left, bottom, right, top = (0.0, 0.0, 1.0, 1.0)

idx.insert(0, (0,0,10,10))
idx.insert(0, (4,4,8,8))

for id in idx.intersection(coordinates=(5,5)):
    print (id)

0
0


In [34]:
import matplotlib.path as mplPath
import numpy as np

poly = [190, 50, 500, 310]
poly_path = mplPath.Path(np.array([ [50, 50],
                                    [50, 100],
                                    [100, 100],
                                    [100, 50]]))
point = ([51, 51],[52, 52])
print(point, " is in polygon: ", poly_path.contains_points(point))

print(point, " is in polygon: ", poly_path.intersects_path())

([51, 51], [52, 52])  is in polygon:  [ True  True]


TypeError: Path.intersects_path() missing 1 required positional argument: 'other'

In [44]:
# https://automating-gis-processes.github.io/CSC18/lessons/L4/point-in-polygon.html
# https://www.matecdev.com/posts/point-in-polygon.html
from shapely.geometry import Point, Polygon

# Create Point objects
p1 = Point(0,0)
p2 = Point(10,10)

# Create a Polygon
coords = [(0,0), (50,0), (50,50), (50,0)]
poly = Polygon(coords)

print (poly.bounds)

print(p1.within(poly))
print(p2.within(poly))
print(poly.intersects(p1))
print(poly.intersects(p2))

(0.0, 0.0, 50.0, 50.0)
False
True
True
True


In [13]:
# https://pygeos.readthedocs.io/en/stable/strtree.html
import pygeos as pg
import numpy as np

point_1 = pg.Geometry("POINT (0 0)")
geometry = pg.Geometry("POLYGON((0 0, 0 10, 10 10, 10 0, 0 0))")

print(point_1)
print(geometry)

# bring in all new positions
tree = pg.STRtree(pg.points(np.arange(10), np.arange(10)))

# Query geometries that overlap envelope of input geometries:

# check for all shapes
tree.query(pg.box(2.1, 2.1, 4, 4)).tolist()
# [2, 3, 4]

# # Query geometries that are contained by input geometry:

# tree.query(pygeos.box(2, 2, 4, 4), predicate='contains').tolist()
# # [3]

# # Query geometries that overlap envelopes of ``geoms``
# tree.query_bulk([pygeos.box(2, 2, 4, 4), pygeos.box(5, 5, 6, 6)]).tolist()
# # [[0, 0, 0, 1, 1], [2, 3, 4, 5, 6]]

# tree.nearest([pygeos.points(1,1), pygeos.points(3,5)]).tolist()  
# # [[0, 1], [1, 4]]

POINT (0 0)
POLYGON ((0 0, 0 10, 10 10, 10 0, 0 0))


[3, 4]

In [100]:
import numpy as np
import pygeos as pg
import geopandas as gp

# https://gis.stackexchange.com/questions/353619/shapely-with-rtree-versus-strtree

points = "10 0 50 8 55 40 20 20 30 50 0 45"

p = np.fromstring(points, sep =" ")

x = p[0::2] # take every second value start by 0
y = p[1::2] # take every second value start by 1

print (x)
print (y)

pointList = np.random.randint(50, size=2*1000000)
# pointList = [-1,-1,10,0]
# print(pointList)

# store points in tree
tree = pg.STRtree(pg.points(pointList[0::2], pointList[1::2]))

# geoms = pg.points()

# pg.creation.polygons(pg.points(points))
# poly = pg.polygons([[0, 0], [0, 10], [10, 10], [10, 0]])
#  p.reshape(-1,2) # the unspecified value is inferred to len(p)/2
coords = p.reshape(-1,2)
poly = pg.polygons(coords)

tree.query(poly)




[10. 50. 55. 20. 30.  0.]
[ 0.  8. 40. 20. 50. 45.]


array([545440, 425011, 528405, ..., 631843, 436503, 942410], dtype=int64)